export default [
    {
        "ID": 1,
        "TopID": 0,
        "AddName": "安徽省"
    },
    {
        "ID": 2,
        "TopID": 0,
        "AddName": "北京市"
    },
    {
        "ID": 3,
        "TopID": 0,
        "AddName": "福建省"
    },
    {
        "ID": 4,
        "TopID": 0,
        "AddName": "甘肃省"
    },
    {
        "ID": 5,
        "TopID": 0,
        "AddName": "广东省"
    },
    {
        "ID": 6,
        "TopID": 0,
        "AddName": "广西壮族自治区"
    }, {
        "ID": 7,
        "TopID": 0,
        "AddName": "贵州省"
    },
    {
        "ID": 8,
        "TopID": 0,
        "AddName": "海南省"
    },
    {
        "ID": 9,
        "TopID": 0,
        "AddName": "河北省"
    }, {
        "ID": 10,
        "TopID": 0,
        "AddName": "河南省"
    },
    {
        "ID": 11,
        "TopID": 0,
        "AddName": "黑龙江省"
    },
    {
        "ID": 12,
        "TopID": 0,
        "AddName": "湖北省"
    }, {
        "ID": 13,
        "TopID": 0,
        "AddName": "湖南省"
    },
    {
        "ID": 14,
        "TopID": 0,
        "AddName": "吉林省"
    }, {
        "ID": 15,
        "TopID": 0,
        "AddName": "江苏省"
    }, {
        "ID": 16,
        "TopID": 0,
        "AddName": "江西省"
    }, {
        "ID": 17,
        "TopID": 0,
        "AddName": "辽宁省"
    }, {
        "ID": 18,
        "TopID": 0,
        "AddName": "内蒙古自治区"
    }, {
        "ID": 19,
        "TopID": 0,
        "AddName": "宁夏回族自治区"
    }, {
        "ID": 20,
        "TopID": 0,
        "AddName": "青海省"
    }, {
        "ID": 21,
        "TopID": 0,
        "AddName": "山东省"
    }, {
        "ID": 22,
        "TopID": 0,
        "AddName": "山西省"
    }, {
        "ID": 23,
        "TopID": 0,
        "AddName": "陕西省"
    }, {
        "ID": 24,
        "TopID": 0,
        "AddName": "上海市"
    }, {
        "ID": 25,
        "TopID": 0,
        "AddName": "四川省"
    }, {
        "ID": 26,
        "TopID": 0,
        "AddName": "天津市"
    }, {
        "ID": 27,
        "TopID": 0,
        "AddName": "西藏自治区"
    }, {
        "ID": 28,
        "TopID": 0,
        "AddName": "新疆自治区"
    }, {
        "ID": 29,
        "TopID": 0,
        "AddName": "云南省"
    }, {
        "ID": 30,
        "TopID": 0,
        "AddName": "浙江省"
    }, {
        "ID": 31,
        "TopID": 0,
        "AddName": "重庆市"
    }, {
        "ID": 32,
        "TopID": 1,
        "AddName": "安庆市"
    }, {
        "ID": 33,
        "TopID": 1,
        "AddName": "蚌埠市"
    }, {
        "ID": 34,
        "TopID": 1,
        "AddName": "亳州市"
    }, {
        "ID": 35,
        "TopID": 1,
        "AddName": "池州市"
    }, {
        "ID": 36,
        "TopID": 1,
        "AddName": "滁州市"
    }, {
        "ID": 37,
        "TopID": 1,
        "AddName": "阜阳市"
    }, {
        "ID": 38,
        "TopID": 1,
        "AddName": "合肥市"
    }, {
        "ID": 39,
        "TopID": 1,
        "AddName": "淮北市"
    }, {
        "ID": 40,
        "TopID": 1,
        "AddName": "淮南市"
    }, {
        "ID": 41,
        "TopID": 1,
        "AddName": "黄山市"
    }, {
        "ID": 42,
        "TopID": 1,
        "AddName": "六安市"
    }, {
        "ID": 43,
        "TopID": 1,
        "AddName": "马鞍山市"
    }, {
        "ID": 44,
        "TopID": 1,
        "AddName": "宿州市"
    }, {
        "ID": 45,
        "TopID": 1,
        "AddName": "铜陵市"
    }, {
        "ID": 46,
        "TopID": 1,
        "AddName": "芜湖市"
    }, {
        "ID": 47,
        "TopID": 1,
        "AddName": "宣城市"
    }, {
        "ID": 48,
        "TopID": 2,
        "AddName": "北京市"
    }, {
        "ID": 49,
        "TopID": 2,
        "AddName": "市辖区"
    }, {
        "ID": 50,
        "TopID": 3,
        "AddName": "福州市"
    }, {
        "ID": 51,
        "TopID": 3,
        "AddName": "龙岩市"
    }, {
        "ID": 52,
        "TopID": 3,
        "AddName": "南平市"
    }, {
        "ID": 53,
        "TopID": 3,
        "AddName": "宁德市"
    }, {
        "ID": 54,
        "TopID": 3,
        "AddName": "莆田市"
    }, {
        "ID": 55,
        "TopID": 3,
        "AddName": "泉州市"
    }, {
        "ID": 56,
        "TopID": 3,
        "AddName": "三明市"
    }, {
        "ID": 57,
        "TopID": 3,
        "AddName": "厦门市"
    }, {
        "ID": 58,
        "TopID": 3,
        "AddName": "漳州市"
    }, {
        "ID": 59,
        "TopID": 4,
        "AddName": "白银市"
    }, {
        "ID": 60,
        "TopID": 4,
        "AddName": "定西市"
    }, {
        "ID": 61,
        "TopID": 4,
        "AddName": "甘南藏族自治州"
    }, {
        "ID": 62,
        "TopID": 4,
        "AddName": "嘉峪关市"
    }, {
        "ID": 63,
        "TopID": 4,
        "AddName": "金昌市"
    }, {
        "ID": 64,
        "TopID": 4,
        "AddName": "酒泉市"
    }, {
        "ID": 65,
        "TopID": 4,
        "AddName": "兰州市"
    }, {
        "ID": 66,
        "TopID": 4,
        "AddName": "临夏回族自治州"
    }, {
        "ID": 67,
        "TopID": 4,
        "AddName": "陇南市"
    }, {
        "ID": 68,
        "TopID": 4,
        "AddName": "平凉市"
    }, {
        "ID": 69,
        "TopID": 4,
        "AddName": "庆阳市"
    }, {
        "ID": 70,
        "TopID": 4,
        "AddName": "天水市"
    }, {
        "ID": 71,
        "TopID": 4,
        "AddName": "武威市"
    }, {
        "ID": 72,
        "TopID": 4,
        "AddName": "张掖市"
    }, {
        "ID": 73,
        "TopID": 5,
        "AddName": "潮州市"
    }, {
        "ID": 74,
        "TopID": 5,
        "AddName": "东莞市"
    }, {
        "ID": 75,
        "TopID": 5,
        "AddName": "佛山市"
    }, {
        "ID": 76,
        "TopID": 5,
        "AddName": "广州市"
    }, {
        "ID": 77,
        "TopID": 5,
        "AddName": "河源市"
    }, {
        "ID": 78,
        "TopID": 5,
        "AddName": "惠州市"
    }, {
        "ID": 79,
        "TopID": 5,
        "AddName": "江门市"
    }, {
        "ID": 80,
        "TopID": 5,
        "AddName": "揭阳市"
    }, {
        "ID": 81,
        "TopID": 5,
        "AddName": "茂名市"
    }, {
        "ID": 82,
        "TopID": 5,
        "AddName": "梅州市"
    }, {
        "ID": 83,
        "TopID": 5,
        "AddName": "清远市"
    }, {
        "ID": 84,
        "TopID": 5,
        "AddName": "汕头市"
    }, {
        "ID": 85,
        "TopID": 5,
        "AddName": "汕尾市"
    }, {
        "ID": 86,
        "TopID": 5,
        "AddName": "韶关市"
    }, {
        "ID": 87,
        "TopID": 5,
        "AddName": "深圳市"
    }, {
        "ID": 88,
        "TopID": 5,
        "AddName": "阳江市"
    }, {
        "ID": 89,
        "TopID": 5,
        "AddName": "云浮市"
    }, {
        "ID": 90,
        "TopID": 5,
        "AddName": "湛江市"
    }, {
        "ID": 91,
        "TopID": 5,
        "AddName": "肇庆市"
    }, {
        "ID": 92,
        "TopID": 5,
        "AddName": "中山市"
    }, {
        "ID": 93,
        "TopID": 5,
        "AddName": "珠海市"
    }, {
        "ID": 94,
        "TopID": 6,
        "AddName": "百色市"
    }, {
        "ID": 95,
        "TopID": 6,
        "AddName": "北海市"
    }, {
        "ID": 96,
        "TopID": 6,
        "AddName": "崇左市"
    }, {
        "ID": 97,
        "TopID": 6,
        "AddName": "防城港市"
    }, {
        "ID": 98,
        "TopID": 6,
        "AddName": "贵港市"
    }, {
        "ID": 99,
        "TopID": 6,
        "AddName": "桂林市"
    }, {
        "ID": 100,
        "TopID": 6,
        "AddName": "河池市"
    }, {
        "ID": 101,
        "TopID": 6,
        "AddName": "贺州市"
    }, {
        "ID": 102,
        "TopID": 6,
        "AddName": "来宾市"
    }, {
        "ID": 103,
        "TopID": 6,
        "AddName": "柳州市"
    }, {
        "ID": 104,
        "TopID": 6,
        "AddName": "南宁市"
    }, {
        "ID": 105,
        "TopID": 6,
        "AddName": "钦州市"
    }, {
        "ID": 106,
        "TopID": 6,
        "AddName": "梧州市"
    }, {
        "ID": 107,
        "TopID": 6,
        "AddName": "玉林市"
    }, {
        "ID": 108,
        "TopID": 7,
        "AddName": "安顺市"
    }, {
        "ID": 109,
        "TopID": 7,
        "AddName": "毕节市"
    }, {
        "ID": 110,
        "TopID": 7,
        "AddName": "贵阳市"
    }, {
        "ID": 111,
        "TopID": 7,
        "AddName": "六盘水市"
    }, {
        "ID": 112,
        "TopID": 7,
        "AddName": "黔东南苗族侗族自治州"
    }, {
        "ID": 113,
        "TopID": 7,
        "AddName": "黔南布依族苗族自治州"
    }, {
        "ID": 114,
        "TopID": 7,
        "AddName": "黔西南布依族苗族自治州"
    }, {
        "ID": 115,
        "TopID": 7,
        "AddName": "铜仁市"
    }, {
        "ID": 116,
        "TopID": 7,
        "AddName": "遵义市"
    }, {
        "ID": 117,
        "TopID": 8,
        "AddName": "海口市"
    }, {
        "ID": 118,
        "TopID": 8,
        "AddName": "三沙市"
    }, {
        "ID": 119,
        "TopID": 8,
        "AddName": "三亚市"
    }, {
        "ID": 120,
        "TopID": 8,
        "AddName": "省直辖县级行政区划"
    }, {
        "ID": 121,
        "TopID": 9,
        "AddName": "保定市"
    }, {
        "ID": 122,
        "TopID": 9,
        "AddName": "沧州市"
    }, {
        "ID": 123,
        "TopID": 9,
        "AddName": "承德市"
    }, {
        "ID": 124,
        "TopID": 9,
        "AddName": "邯郸市"
    }, {
        "ID": 125,
        "TopID": 9,
        "AddName": "衡水市"
    }, {
        "ID": 126,
        "TopID": 9,
        "AddName": "廊坊市"
    }, {
        "ID": 127,
        "TopID": 9,
        "AddName": "秦皇岛市"
    }, {
        "ID": 128,
        "TopID": 9,
        "AddName": "石家庄市"
    }, {
        "ID": 129,
        "TopID": 9,
        "AddName": "唐山市"
    }, {
        "ID": 130,
        "TopID": 9,
        "AddName": "邢台市"
    }, {
        "ID": 131,
        "TopID": 9,
        "AddName": "张家口市"
    }, {
        "ID": 132,
        "TopID": 10,
        "AddName": "安阳市"
    }, {
        "ID": 133,
        "TopID": 10,
        "AddName": "鹤壁市"
    }, {
        "ID": 134,
        "TopID": 10,
        "AddName": "焦作市"
    }, {
        "ID": 135,
        "TopID": 10,
        "AddName": "开封市"
    }, {
        "ID": 136,
        "TopID": 10,
        "AddName": "洛阳市"
    }, {
        "ID": 137,
        "TopID": 10,
        "AddName": "漯河市"
    }, {
        "ID": 138,
        "TopID": 10,
        "AddName": "南阳市"
    }, {
        "ID": 139,
        "TopID": 10,
        "AddName": "平顶山市"
    }, {
        "ID": 140,
        "TopID": 10,
        "AddName": "濮阳市"
    }, {
        "ID": 141,
        "TopID": 10,
        "AddName": "三门峡市"
    }, {
        "ID": 142,
        "TopID": 10,
        "AddName": "商丘市"
    }, {
        "ID": 143,
        "TopID": 10,
        "AddName": "省直辖县级行政区划"
    }, {
        "ID": 144,
        "TopID": 10,
        "AddName": "新乡市"
    }, {
        "ID": 145,
        "TopID": 10,
        "AddName": "信阳市"
    }, {
        "ID": 146,
        "TopID": 10,
        "AddName": "许昌市"
    }, {
        "ID": 147,
        "TopID": 10,
        "AddName": "郑州市"
    }, {
        "ID": 148,
        "TopID": 10,
        "AddName": "周口市"
    }, {
        "ID": 149,
        "TopID": 10,
        "AddName": "驻马店市"
    }, {
        "ID": 150,
        "TopID": 11,
        "AddName": "大庆市"
    }, {
        "ID": 151,
        "TopID": 11,
        "AddName": "大兴安岭地区"
    }, {
        "ID": 152,
        "TopID": 11,
        "AddName": "哈尔滨市"
    }, {
        "ID": 153,
        "TopID": 11,
        "AddName": "鹤岗市"
    }, {
        "ID": 154,
        "TopID": 11,
        "AddName": "黑河市"
    }, {
        "ID": 155,
        "TopID": 11,
        "AddName": "鸡西市"
    }, {
        "ID": 156,
        "TopID": 11,
        "AddName": "佳木斯市"
    }, {
        "ID": 157,
        "TopID": 11,
        "AddName": "牡丹江市"
    }, {
        "ID": 158,
        "TopID": 11,
        "AddName": "七台河市"
    }, {
        "ID": 159,
        "TopID": 11,
        "AddName": "齐齐哈尔市"
    }, {
        "ID": 160,
        "TopID": 11,
        "AddName": "双鸭山市"
    }, {
        "ID": 161,
        "TopID": 11,
        "AddName": "绥化市"
    }, {
        "ID": 162,
        "TopID": 11,
        "AddName": "伊春市"
    }, {
        "ID": 163,
        "TopID": 12,
        "AddName": "鄂州市"
    }, {
        "ID": 164,
        "TopID": 12,
        "AddName": "恩施土家族苗族自治州"
    }, {
        "ID": 165,
        "TopID": 12,
        "AddName": "黄冈市"
    }, {
        "ID": 166,
        "TopID": 12,
        "AddName": "黄石市"
    }, {
        "ID": 167,
        "TopID": 12,
        "AddName": "荆门市"
    }, {
        "ID": 168,
        "TopID": 12,
        "AddName": "荆州市"
    }, {
        "ID": 169,
        "TopID": 12,
        "AddName": "省直辖县级行政区划"
    }, {
        "ID": 170,
        "TopID": 12,
        "AddName": "十堰市"
    }, {
        "ID": 171,
        "TopID": 12,
        "AddName": "随州市"
    }, {
        "ID": 172,
        "TopID": 12,
        "AddName": "武汉市"
    }, {
        "ID": 173,
        "TopID": 12,
        "AddName": "咸宁市"
    }, {
        "ID": 174,
        "TopID": 12,
        "AddName": "襄阳市"
    }, {
        "ID": 175,
        "TopID": 12,
        "AddName": "孝感市"
    }, {
        "ID": 176,
        "TopID": 12,
        "AddName": "宜昌市"
    }, {
        "ID": 177,
        "TopID": 13,
        "AddName": "长沙市"
    }, {
        "ID": 178,
        "TopID": 13,
        "AddName": "常德市"
    }, {
        "ID": 179,
        "TopID": 13,
        "AddName": "郴州市"
    }, {
        "ID": 180,
        "TopID": 13,
        "AddName": "衡阳市"
    }, {
        "ID": 181,
        "TopID": 13,
        "AddName": "怀化市"
    }, {
        "ID": 182,
        "TopID": 13,
        "AddName": "娄底市"
    }, {
        "ID": 183,
        "TopID": 13,
        "AddName": "邵阳市"
    }, {
        "ID": 184,
        "TopID": 13,
        "AddName": "湘潭市"
    }, {
        "ID": 185,
        "TopID": 13,
        "AddName": "湘西土家族苗族自治州"
    }, {
        "ID": 186,
        "TopID": 13,
        "AddName": "益阳市"
    }, {
        "ID": 187,
        "TopID": 13,
        "AddName": "永州市"
    }, {
        "ID": 188,
        "TopID": 13,
        "AddName": "岳阳市"
    }, {
        "ID": 189,
        "TopID": 13,
        "AddName": "张家界市"
    }, {
        "ID": 190,
        "TopID": 13,
        "AddName": "株洲市"
    }, {
        "ID": 191,
        "TopID": 14,
        "AddName": "白城市"
    }, {
        "ID": 192,
        "TopID": 14,
        "AddName": "白山市"
    }, {
        "ID": 193,
        "TopID": 14,
        "AddName": "长春市"
    }, {
        "ID": 194,
        "TopID": 14,
        "AddName": "吉林市"
    }, {
        "ID": 195,
        "TopID": 14,
        "AddName": "辽源市"
    }, {
        "ID": 196,
        "TopID": 14,
        "AddName": "四平市"
    }, {
        "ID": 197,
        "TopID": 14,
        "AddName": "松原市"
    }, {
        "ID": 198,
        "TopID": 14,
        "AddName": "通化市"
    }, {
        "ID": 199,
        "TopID": 14,
        "AddName": "延边朝鲜族自治州"
    }, {
        "ID": 200,
        "TopID": 15,
        "AddName": "常州市"
    }, {
        "ID": 201,
        "TopID": 15,
        "AddName": "淮安市"
    }, {
        "ID": 202,
        "TopID": 15,
        "AddName": "连云港市"
    }, {
        "ID": 203,
        "TopID": 15,
        "AddName": "南京市"
    }, {
        "ID": 204,
        "TopID": 15,
        "AddName": "南通市"
    }, {
        "ID": 205,
        "TopID": 15,
        "AddName": "苏州市"
    }, {
        "ID": 206,
        "TopID": 15,
        "AddName": "宿迁市"
    }, {
        "ID": 207,
        "TopID": 15,
        "AddName": "泰州市"
    }, {
        "ID": 208,
        "TopID": 15,
        "AddName": "无锡市"
    }, {
        "ID": 209,
        "TopID": 15,
        "AddName": "徐州市"
    }, {
        "ID": 210,
        "TopID": 15,
        "AddName": "盐城市"
    }, {
        "ID": 211,
        "TopID": 15,
        "AddName": "扬州市"
    }, {
        "ID": 212,
        "TopID": 15,
        "AddName": "镇江市"
    }, {
        "ID": 213,
        "TopID": 16,
        "AddName": "抚州市"
    }, {
        "ID": 214,
        "TopID": 16,
        "AddName": "赣州市"
    }, {
        "ID": 215,
        "TopID": 16,
        "AddName": "吉安市"
    }, {
        "ID": 216,
        "TopID": 16,
        "AddName": "景德镇市"
    }, {
        "ID": 217,
        "TopID": 16,
        "AddName": "九江市"
    }, {
        "ID": 218,
        "TopID": 16,
        "AddName": "南昌市"
    }, {
        "ID": 219,
        "TopID": 16,
        "AddName": "萍乡市"
    }, {
        "ID": 220,
        "TopID": 16,
        "AddName": "上饶市"
    }, {
        "ID": 221,
        "TopID": 16,
        "AddName": "新余市"
    }, {
        "ID": 222,
        "TopID": 16,
        "AddName": "宜春市"
    }, {
        "ID": 223,
        "TopID": 16,
        "AddName": "鹰潭市"
    }, {
        "ID": 224,
        "TopID": 17,
        "AddName": "鞍山市"
    }, {
        "ID": 225,
        "TopID": 17,
        "AddName": "本溪市"
    }, {
        "ID": 226,
        "TopID": 17,
        "AddName": "朝阳市"
    }, {
        "ID": 227,
        "TopID": 17,
        "AddName": "大连市"
    }, {
        "ID": 228,
        "TopID": 17,
        "AddName": "丹东市"
    }, {
        "ID": 229,
        "TopID": 17,
        "AddName": "抚顺市"
    }, {
        "ID": 230,
        "TopID": 17,
        "AddName": "阜新市"
    }, {
        "ID": 231,
        "TopID": 17,
        "AddName": "葫芦岛市"
    }, {
        "ID": 232,
        "TopID": 17,
        "AddName": "锦州市"
    }, {
        "ID": 233,
        "TopID": 17,
        "AddName": "辽阳市"
    }, {
        "ID": 234,
        "TopID": 17,
        "AddName": "盘锦市"
    }, {
        "ID": 235,
        "TopID": 17,
        "AddName": "沈阳市"
    }, {
        "ID": 236,
        "TopID": 17,
        "AddName": "铁岭市"
    }, {
        "ID": 237,
        "TopID": 17,
        "AddName": "营口市"
    }, {
        "ID": 238,
        "TopID": 18,
        "AddName": "阿拉善盟"
    }, {
        "ID": 239,
        "TopID": 18,
        "AddName": "巴彦淖尔市"
    }, {
        "ID": 240,
        "TopID": 18,
        "AddName": "包头市"
    }, {
        "ID": 241,
        "TopID": 18,
        "AddName": "赤峰市"
    }, {
        "ID": 242,
        "TopID": 18,
        "AddName": "鄂尔多斯市"
    }, {
        "ID": 243,
        "TopID": 18,
        "AddName": "呼和浩特市"
    }, {
        "ID": 244,
        "TopID": 18,
        "AddName": "呼伦贝尔市"
    }, {
        "ID": 245,
        "TopID": 18,
        "AddName": "通辽市"
    }, {
        "ID": 246,
        "TopID": 18,
        "AddName": "乌海市"
    }, {
        "ID": 247,
        "TopID": 18,
        "AddName": "乌兰察布市"
    }, {
        "ID": 248,
        "TopID": 18,
        "AddName": "锡林郭勒盟"
    }, {
        "ID": 249,
        "TopID": 18,
        "AddName": "兴安盟"
    }, {
        "ID": 250,
        "TopID": 19,
        "AddName": "固原市"
    }, {
        "ID": 251,
        "TopID": 19,
        "AddName": "石嘴山市"
    }, {
        "ID": 252,
        "TopID": 19,
        "AddName": "吴忠市"
    }, {
        "ID": 253,
        "TopID": 19,
        "AddName": "银川市"
    }, {
        "ID": 254,
        "TopID": 19,
        "AddName": "中卫市"
    }, {
        "ID": 255,
        "TopID": 20,
        "AddName": "果洛藏族自治州"
    }, {
        "ID": 256,
        "TopID": 20,
        "AddName": "海北藏族自治州"
    }, {
        "ID": 257,
        "TopID": 20,
        "AddName": "海东地区"
    }, {
        "ID": 258,
        "TopID": 20,
        "AddName": "海南藏族自治州"
    }, {
        "ID": 259,
        "TopID": 20,
        "AddName": "海西蒙古族藏族自治州"
    }, {
        "ID": 260,
        "TopID": 20,
        "AddName": "黄南藏族自治州"
    }, {
        "ID": 261,
        "TopID": 20,
        "AddName": "西宁市"
    }, {
        "ID": 262,
        "TopID": 20,
        "AddName": "玉树藏族自治州"
    }, {
        "ID": 263,
        "TopID": 21,
        "AddName": "滨州市"
    }, {
        "ID": 264,
        "TopID": 21,
        "AddName": "德州市"
    }, {
        "ID": 265,
        "TopID": 21,
        "AddName": "东营市"
    }, {
        "ID": 266,
        "TopID": 21,
        "AddName": "菏泽市"
    }, {
        "ID": 267,
        "TopID": 21,
        "AddName": "济南市"
    }, {
        "ID": 268,
        "TopID": 21,
        "AddName": "济宁市"
    }, {
        "ID": 269,
        "TopID": 21,
        "AddName": "莱芜市"
    }, {
        "ID": 270,
        "TopID": 21,
        "AddName": "聊城市"
    }, {
        "ID": 271,
        "TopID": 21,
        "AddName": "临沂市"
    }, {
        "ID": 272,
        "TopID": 21,
        "AddName": "青岛市"
    }, {
        "ID": 273,
        "TopID": 21,
        "AddName": "日照市"
    }, {
        "ID": 274,
        "TopID": 21,
        "AddName": "泰安市"
    }, {
        "ID": 275,
        "TopID": 21,
        "AddName": "威海市"
    }, {
        "ID": 276,
        "TopID": 21,
        "AddName": "潍坊市"
    }, {
        "ID": 277,
        "TopID": 21,
        "AddName": "烟台市"
    }, {
        "ID": 278,
        "TopID": 21,
        "AddName": "枣庄市"
    }, {
        "ID": 279,
        "TopID": 21,
        "AddName": "淄博市"
    }, {
        "ID": 280,
        "TopID": 22,
        "AddName": "长治市"
    }, {
        "ID": 281,
        "TopID": 22,
        "AddName": "大同市"
    }, {
        "ID": 282,
        "TopID": 22,
        "AddName": "晋城市"
    }, {
        "ID": 283,
        "TopID": 22,
        "AddName": "晋中市"
    }, {
        "ID": 284,
        "TopID": 22,
        "AddName": "临汾市"
    }, {
        "ID": 285,
        "TopID": 22,
        "AddName": "吕梁市"
    }, {
        "ID": 286,
        "TopID": 22,
        "AddName": "朔州市"
    }, {
        "ID": 287,
        "TopID": 22,
        "AddName": "太原市"
    }, {
        "ID": 288,
        "TopID": 22,
        "AddName": "忻州市"
    }, {
        "ID": 289,
        "TopID": 22,
        "AddName": "阳泉市"
    }, {
        "ID": 290,
        "TopID": 22,
        "AddName": "运城市"
    }, {
        "ID": 291,
        "TopID": 23,
        "AddName": "安康市"
    }, {
        "ID": 292,
        "TopID": 23,
        "AddName": "宝鸡市"
    }, {
        "ID": 293,
        "TopID": 23,
        "AddName": "汉中市"
    }, {
        "ID": 294,
        "TopID": 23,
        "AddName": "商洛市"
    }, {
        "ID": 295,
        "TopID": 23,
        "AddName": "铜川市"
    }, {
        "ID": 296,
        "TopID": 23,
        "AddName": "渭南市"
    }, {
        "ID": 297,
        "TopID": 23,
        "AddName": "西安市"
    }, {
        "ID": 298,
        "TopID": 23,
        "AddName": "咸阳市"
    }, {
        "ID": 299,
        "TopID": 23,
        "AddName": "延安市"
    }, {
        "ID": 300,
        "TopID": 23,
        "AddName": "榆林市"
    }, {
        "ID": 301,
        "TopID": 24,
        "AddName": "上海市"
    }, {
        "ID": 302,
        "TopID": 25,
        "AddName": "阿坝藏族羌族自治州"
    }, {
        "ID": 303,
        "TopID": 25,
        "AddName": "巴中市"
    }, {
        "ID": 304,
        "TopID": 25,
        "AddName": "成都市"
    }, {
        "ID": 305,
        "TopID": 25,
        "AddName": "达州市"
    }, {
        "ID": 306,
        "TopID": 25,
        "AddName": "德阳市"
    }, {
        "ID": 307,
        "TopID": 25,
        "AddName": "甘孜藏族自治州"
    }, {
        "ID": 308,
        "TopID": 25,
        "AddName": "广安市"
    }, {
        "ID": 309,
        "TopID": 25,
        "AddName": "广元市"
    }, {
        "ID": 310,
        "TopID": 25,
        "AddName": "乐山市"
    }, {
        "ID": 311,
        "TopID": 25,
        "AddName": "凉山彝族自治州"
    }, {
        "ID": 312,
        "TopID": 25,
        "AddName": "泸州市"
    }, {
        "ID": 313,
        "TopID": 25,
        "AddName": "眉山市"
    }, {
        "ID": 314,
        "TopID": 25,
        "AddName": "绵阳市"
    }, {
        "ID": 315,
        "TopID": 25,
        "AddName": "内江市"
    }, {
        "ID": 316,
        "TopID": 25,
        "AddName": "南充市"
    }, {
        "ID": 317,
        "TopID": 25,
        "AddName": "攀枝花市"
    }, {
        "ID": 318,
        "TopID": 25,
        "AddName": "遂宁市"
    }, {
        "ID": 319,
        "TopID": 25,
        "AddName": "雅安市"
    }, {
        "ID": 320,
        "TopID": 25,
        "AddName": "宜宾市"
    }, {
        "ID": 321,
        "TopID": 25,
        "AddName": "资阳市"
    }, {
        "ID": 322,
        "TopID": 25,
        "AddName": "自贡市"
    }, {
        "ID": 323,
        "TopID": 26,
        "AddName": "天津市"
    }, {
        "ID": 324,
        "TopID": 27,
        "AddName": "阿里地区"
    }, {
        "ID": 325,
        "TopID": 27,
        "AddName": "昌都地区"
    }, {
        "ID": 326,
        "TopID": 27,
        "AddName": "拉萨市"
    }, {
        "ID": 327,
        "TopID": 27,
        "AddName": "林芝地区"
    }, {
        "ID": 328,
        "TopID": 27,
        "AddName": "那曲地区"
    }, {
        "ID": 329,
        "TopID": 27,
        "AddName": "日喀则地区"
    }, {
        "ID": 330,
        "TopID": 27,
        "AddName": "山南地区"
    }, {
        "ID": 331,
        "TopID": 28,
        "AddName": "阿克苏地区"
    }, {
        "ID": 332,
        "TopID": 28,
        "AddName": "阿勒泰地区"
    }, {
        "ID": 333,
        "TopID": 28,
        "AddName": "巴音郭楞蒙古自治州"
    }, {
        "ID": 334,
        "TopID": 28,
        "AddName": "博尔塔拉蒙古自治州"
    }, {
        "ID": 335,
        "TopID": 28,
        "AddName": "昌吉回族自治州"
    }, {
        "ID": 336,
        "TopID": 28,
        "AddName": "哈密地区"
    }, {
        "ID": 337,
        "TopID": 28,
        "AddName": "和田地区"
    }, {
        "ID": 338,
        "TopID": 28,
        "AddName": "喀什地区"
    }, {
        "ID": 339,
        "TopID": 28,
        "AddName": "克拉玛依市"
    }, {
        "ID": 340,
        "TopID": 28,
        "AddName": "克孜勒苏柯尔克孜自治州"
    }, {
        "ID": 341,
        "TopID": 28,
        "AddName": "塔城地区"
    }, {
        "ID": 342,
        "TopID": 28,
        "AddName": "吐鲁番地区"
    }, {
        "ID": 343,
        "TopID": 28,
        "AddName": "乌鲁木齐市"
    }, {
        "ID": 344,
        "TopID": 28,
        "AddName": "伊犁哈萨克自治州"
    }, {
        "ID": 345,
        "TopID": 28,
        "AddName": "自治区直辖县级行政区划"
    }, {
        "ID": 346,
        "TopID": 29,
        "AddName": "保山市"
    }, {
        "ID": 347,
        "TopID": 29,
        "AddName": "楚雄彝族自治州"
    }, {
        "ID": 348,
        "TopID": 29,
        "AddName": "大理白族自治州"
    }, {
        "ID": 349,
        "TopID": 29,
        "AddName": "德宏傣族景颇族自治州"
    }, {
        "ID": 350,
        "TopID": 29,
        "AddName": "迪庆藏族自治州"
    }, {
        "ID": 351,
        "TopID": 29,
        "AddName": "红河哈尼族彝族自治州"
    }, {
        "ID": 352,
        "TopID": 29,
        "AddName": "昆明市"
    }, {
        "ID": 353,
        "TopID": 29,
        "AddName": "丽江市"
    }, {
        "ID": 354,
        "TopID": 29,
        "AddName": "临沧市"
    }, {
        "ID": 355,
        "TopID": 29,
        "AddName": "怒江傈僳族自治州"
    }, {
        "ID": 356,
        "TopID": 29,
        "AddName": "普洱市"
    }, {
        "ID": 357,
        "TopID": 29,
        "AddName": "曲靖市"
    }, {
        "ID": 358,
        "TopID": 29,
        "AddName": "文山壮族苗族自治州"
    }, {
        "ID": 359,
        "TopID": 29,
        "AddName": "西双版纳傣族自治州"
    }, {
        "ID": 360,
        "TopID": 29,
        "AddName": "玉溪市"
    }, {
        "ID": 361,
        "TopID": 29,
        "AddName": "昭通市"
    }, {
        "ID": 362,
        "TopID": 30,
        "AddName": "杭州市"
    }, {
        "ID": 363,
        "TopID": 30,
        "AddName": "湖州市"
    }, {
        "ID": 364,
        "TopID": 30,
        "AddName": "嘉兴市"
    }, {
        "ID": 365,
        "TopID": 30,
        "AddName": "金华市"
    }, {
        "ID": 366,
        "TopID": 30,
        "AddName": "丽水市"
    }, {
        "ID": 367,
        "TopID": 30,
        "AddName": "宁波市"
    }, {
        "ID": 368,
        "TopID": 30,
        "AddName": "衢州市"
    }, {
        "ID": 369,
        "TopID": 30,
        "AddName": "绍兴市"
    }, {
        "ID": 370,
        "TopID": 30,
        "AddName": "台州市"
    }, {
        "ID": 371,
        "TopID": 30,
        "AddName": "温州市"
    }, {
        "ID": 372,
        "TopID": 30,
        "AddName": "舟山市"
    }, {
        "ID": 373,
        "TopID": 31,
        "AddName": "重庆市"
    }
]